// /api/doc/recommendations?condition=toothache
const diseaseToSpeciality = {
  fever: "General Practitioner",
  toothache: "Dentist",
  "skin rash": "Dermatologist",
  diabetes: "Endocrinologist",
  hypertension: "Cardiologist",
  asthma: "Pulmonologist",
  depression: "Psychiatrist",
  anxiety: "Psychiatrist",
  arthritis: "Rheumatologist",
  "back pain": "Orthopedist",
  migraine: "Neurologist",
  "heart disease": "Cardiologist",
  "chest pain": "Cardiologist",
  pneumonia: "Pulmonologist",
  bronchitis: "Pulmonologist",
  "ear infection": "ENT Specialist",
  sinusitis: "ENT Specialist",
  "urinary tract infection": "Urologist",
  "kidney stones": "Urologist",
  allergies: "Allergist",
  eczema: "Dermatologist",
  psoriasis: "Dermatologist",
  obesity: "Endocrinologist",
  "thyroid issues": "Endocrinologist",
  "menstrual disorders": "Gynecologist",
  pregnancy: "Obstetrician",
  infertility: "Reproductive Endocrinologist",
  "eye infection": "Ophthalmologist",
  glaucoma: "Ophthalmologist",
  cataracts: "Ophthalmologist",
  "high cholesterol": "Cardiologist",
  anemia: "Hematologist",
  leukemia: "Hematologist",
  lymphoma: "Oncologist",
  "breast cancer": "Oncologist",
  "prostate cancer": "Urologist",
  "colon cancer": "Gastroenterologist",
  "stomach ulcers": "Gastroenterologist",
  "irritable bowel syndrome": "Gastroenterologist",
  hepatitis: "Hepatologist",
  "liver cirrhosis": "Hepatologist",
  gallstones: "Gastroenterologist",
  appendicitis: "General Surgeon",
  hernias: "General Surgeon",
  stroke: "Neurologist",
  epilepsy: "Neurologist",
  "multiple sclerosis": "Neurologist",
  "parkinson's disease": "Neurologist",
  "alzheimer's disease": "Neurologist",
  "bipolar disorder": "Psychiatrist",
  schizophrenia: "Psychiatrist",
};

module.exports = diseaseToSpeciality;
